version: "3.7"

services:
  db:
    image: mysql:8
    ports:
      - 1527:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

volumes:
  mysql-data:
